import React, { useState, useEffect, useRef } from 'react';
import { useAuth } from '../context/AuthContext';
import { reportsAPI } from '../services/api';
import {
  FileBarChart, Download, Calendar,
  TrendingUp, TrendingDown, PieChart,
  AlertCircle, RefreshCw, Filter,
} from 'lucide-react';
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, BarChart, Bar, Legend,
  PieChart as RechartsPie, Pie, Cell,
} from 'recharts';
import './PageStyles.css';

// ── jsPDF loader via CDN (no npm install needed) ────────────────────────────
const loadPDFLibs = () => new Promise((resolve, reject) => {
  // If already loaded, resolve immediately
  if (window.jspdf && window.jspdf.jsPDF) {
    resolve();
    return;
  }
  // Load jsPDF first, then autoTable
  const s1 = document.createElement('script');
  s1.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
  s1.onload = () => {
    const s2 = document.createElement('script');
    s2.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.2/jspdf.plugin.autotable.min.js';
    s2.onload = () => resolve();
    s2.onerror = reject;
    document.head.appendChild(s2);
  };
  s1.onerror = reject;
  document.head.appendChild(s1);
});

const COLORS = ['#16a34a', '#2563eb', '#d97706', '#dc2626', '#7c3aed', '#db2777'];

const TOOLTIP_STYLE = {
  backgroundColor: '#ffffff',
  border: '1px solid #e2e8f0',
  borderRadius: '8px',
  boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
  fontSize: '13px',
};

// ── Currency formatter ───────────────────────────────────────────────────────
const fmtNPR = (v) =>
  new Intl.NumberFormat('en-NP', {
    style: 'currency', currency: 'NPR', minimumFractionDigits: 0,
  }).format(v || 0);

// ── PDF builder ──────────────────────────────────────────────────────────────
const buildPDF = (doc, reportType, data, user, organization) => {
  const GREEN  = [22, 163, 74];
  const RED    = [220, 38, 38];
  const BLUE   = [37, 99, 235];
  const DARK   = [15, 23, 42];
  const GRAY   = [100, 116, 139];
  const LGRAY  = [248, 250, 252];
  const WHITE  = [255, 255, 255];

  const PW = doc.internal.pageSize.getWidth();
  const PH = doc.internal.pageSize.getHeight();
  const ML = 14;
  const MR = PW - ML;
  const CW = MR - ML;

  const reportTitles = {
    financial : 'Financial Report',
    budget    : 'Budget Performance Report',
    trends    : 'Expense Trends Report',
    department: 'Department-wise Report',
  };

  const now     = new Date();
  const dateStr = now.toLocaleDateString('en-NP', { year: 'numeric', month: 'long', day: 'numeric' });
  const orgName = organization?.name || 'Organization';
  const userName = `${user?.firstName || ''} ${user?.lastName || ''}`.trim();

  // ── Header bar ──────────────────────────────────────────────────────────
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, PW, 28, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...WHITE);
  doc.text('BudMap', ML, 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Budget Management Application — Nepal', ML, 19);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text(reportTitles[reportType] || 'Report', MR, 12, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(`${orgName}  |  ${dateStr}`, MR, 19, { align: 'right' });

  // ── Sub-header ──────────────────────────────────────────────────────────
  doc.setFillColor(240, 253, 244);
  doc.rect(0, 28, PW, 10, 'F');
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(`Generated by: ${userName}   |   ${now.toLocaleTimeString()}`, ML, 34);
  doc.text('CONFIDENTIAL', MR, 34, { align: 'right' });

  let y = 44;

  // ── helper: section title ───────────────────────────────────────────────
  const sectionTitle = (title, yPos) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...DARK);
    doc.text(title, ML, yPos);
    doc.setDrawColor(...GREEN);
    doc.setLineWidth(0.5);
    doc.line(ML, yPos + 1.5, MR, yPos + 1.5);
    return yPos + 8;
  };

  // ── helper: summary boxes (4 across) ───────────────────────────────────
  const summaryBoxes = (boxes, yPos) => {
    const bw = (CW - 6) / boxes.length;
    boxes.forEach((b, i) => {
      const x = ML + i * (bw + 2);
      doc.setFillColor(...LGRAY);
      doc.roundedRect(x, yPos, bw, 18, 2, 2, 'F');
      doc.setDrawColor(...b.color);
      doc.setLineWidth(0.8);
      doc.line(x, yPos, x, yPos + 18);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(...GRAY);
      doc.text(b.label, x + 3, yPos + 6);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(...DARK);
      doc.text(String(b.value), x + 3, yPos + 14);
    });
    return yPos + 24;
  };

  // ── helper: autoTable wrapper ───────────────────────────────────────────
  const autoT = (head, body, startY) => {
    doc.autoTable({
      head,
      body,
      startY,
      margin: { left: ML, right: ML },
      styles: { fontSize: 8, cellPadding: 3, textColor: DARK, lineColor: [226, 232, 240], lineWidth: 0.2 },
      headStyles: { fillColor: [30, 81, 40], textColor: WHITE, fontStyle: 'bold', fontSize: 8 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: {},
      tableWidth: CW,
    });
    return doc.lastAutoTable.finalY + 6;
  };

  // ── helper: page check ─────────────────────────────────────────────────
  const needsPage = (curY, needed = 30) => {
    if (curY + needed > PH - 20) {
      doc.addPage();
      return 20;
    }
    return curY;
  };

  // ════════════════════════════════════════════════════════════════════════
  //  FINANCIAL REPORT
  // ════════════════════════════════════════════════════════════════════════
  if (reportType === 'financial' && data) {
    const { summary, categoryBreakdown = [], departmentBreakdown = [], monthlyTrend = [] } = data;

    y = sectionTitle('Financial Summary', y);
    y = summaryBoxes([
      { label: 'Total Income',    value: fmtNPR(summary.totalIncome),  color: GREEN },
      { label: 'Total Expense',   value: fmtNPR(summary.totalExpense), color: RED   },
      { label: 'Net Amount',      value: fmtNPR(summary.netAmount),    color: BLUE  },
      { label: 'Transactions',    value: String(summary.transactionCount || 0), color: GRAY },
    ], y);

    if (monthlyTrend.length > 0) {
      y = needsPage(y, 40);
      y = sectionTitle('Monthly Trend', y);
      y = autoT(
        [['Month', 'Income (NPR)', 'Expense (NPR)', 'Net (NPR)']],
        monthlyTrend.map(m => [
          m.month,
          fmtNPR(m.income),
          fmtNPR(m.expense),
          fmtNPR(m.income - m.expense),
        ]),
        y
      );
    }

    if (categoryBreakdown.length > 0) {
      y = needsPage(y, 40);
      y = sectionTitle('Category Breakdown', y);
      y = autoT(
        [['Category', 'Type', 'Amount (NPR)', 'Transactions']],
        categoryBreakdown.map(c => [c.name, c.type, fmtNPR(c.amount), String(c.count)]),
        y
      );
    }

    if (departmentBreakdown.length > 0) {
      y = needsPage(y, 40);
      y = sectionTitle('Department Breakdown', y);
      y = autoT(
        [['Department', 'Income (NPR)', 'Expense (NPR)', 'Transactions']],
        departmentBreakdown.map(d => [d.name, fmtNPR(d.income), fmtNPR(d.expense), String(d.count)]),
        y
      );
    }
  }

  // ════════════════════════════════════════════════════════════════════════
  //  BUDGET PERFORMANCE
  // ════════════════════════════════════════════════════════════════════════
  else if (reportType === 'budget' && data) {
    const { summary, budgets = [] } = data;

    y = sectionTitle('Budget Summary', y);
    y = summaryBoxes([
      { label: 'Total Budgets',   value: String(summary.totalBudgets),         color: BLUE  },
      { label: 'Total Budgeted',  value: fmtNPR(summary.totalBudgeted),        color: GREEN },
      { label: 'Total Spent',     value: fmtNPR(summary.totalSpent),           color: RED   },
      { label: 'Avg Utilization', value: `${summary.averageUtilization}%`,     color: GRAY  },
    ], y);

    // Status counts
    y = needsPage(y, 20);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text(
      `Healthy: ${summary.healthyCount}   Warning: ${summary.warningCount}   Overspent: ${summary.overspentCount}   Active: ${summary.activeBudgets}`,
      ML, y
    );
    y += 8;

    if (budgets.length > 0) {
      y = needsPage(y, 40);
      y = sectionTitle('Budget Details', y);
      y = autoT(
        [['Budget Name', 'Department', 'Total (NPR)', 'Spent (NPR)', 'Remaining (NPR)', 'Utilization', 'Status']],
        budgets.map(b => [
          b.name,
          b.department,
          fmtNPR(b.totalAmount),
          fmtNPR(b.spentAmount),
          fmtNPR(b.remainingAmount),
          `${b.utilizationRate}%`,
          b.status,
        ]),
        y
      );
    }
  }

  // ════════════════════════════════════════════════════════════════════════
  //  EXPENSE TRENDS
  // ════════════════════════════════════════════════════════════════════════
  else if (reportType === 'trends' && data) {
    const { summary, monthlyData = [], topCategories = [] } = data;

    y = sectionTitle('Expense Trends Summary', y);
    y = summaryBoxes([
      { label: 'Total Expense',  value: fmtNPR(summary.totalExpense),       color: RED   },
      { label: 'Avg Monthly',    value: fmtNPR(summary.avgMonthlyExpense),  color: BLUE  },
      { label: 'Total Income',   value: fmtNPR(summary.totalIncome),        color: GREEN },
      { label: 'Trend',          value: data.trend || '—',                  color: GRAY  },
    ], y);

    if (monthlyData.length > 0) {
      y = needsPage(y, 40);
      y = sectionTitle('Monthly Breakdown', y);
      y = autoT(
        [['Month', 'Income (NPR)', 'Expense (NPR)', 'Transactions']],
        monthlyData.map(m => [m.month, fmtNPR(m.income), fmtNPR(m.expense), String(m.transactions)]),
        y
      );
    }

    if (topCategories.length > 0) {
      y = needsPage(y, 40);
      y = sectionTitle('Top Expense Categories', y);
      y = autoT(
        [['Rank', 'Category', 'Amount (NPR)', 'Transactions']],
        topCategories.map((c, i) => [`#${i + 1}`, c.name, fmtNPR(c.amount), String(c.count)]),
        y
      );
    }
  }

  // ════════════════════════════════════════════════════════════════════════
  //  DEPARTMENT-WISE
  // ════════════════════════════════════════════════════════════════════════
  else if (reportType === 'department' && data) {
    const { departments = [], summary } = data;

    y = sectionTitle('Department Overview', y);
    y = summaryBoxes([
      { label: 'Departments',    value: String(summary.totalDepartments),  color: BLUE  },
      { label: 'Total Budgeted', value: fmtNPR(summary.totalBudgeted),    color: GREEN },
      { label: 'Total Spent',    value: fmtNPR(summary.totalSpent),       color: RED   },
      { label: 'Transactions',   value: String(summary.totalTransactions), color: GRAY  },
    ], y);

    if (departments.length > 0) {
      y = needsPage(y, 40);
      y = sectionTitle('Department Details', y);
      y = autoT(
        [['Department', 'Head', 'Budgeted (NPR)', 'Spent (NPR)', 'Remaining (NPR)', 'Utilization', 'Transactions']],
        departments.map(d => [
          d.name,
          d.head,
          fmtNPR(d.totalBudgeted),
          fmtNPR(d.totalSpent),
          fmtNPR(d.remainingBudget),
          `${d.utilizationRate}%`,
          String(d.transactionCount),
        ]),
        y
      );
    }
  }

  // ── Footer on every page ────────────────────────────────────────────────
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFillColor(240, 253, 244);
    doc.rect(0, PH - 12, PW, 12, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...GRAY);
    doc.text('BudMap — Confidential Financial Report', ML, PH - 4);
    doc.text(`Page ${p} of ${totalPages}`, MR, PH - 4, { align: 'right' });
  }
};

// ════════════════════════════════════════════════════════════════════════════
//  COMPONENT
// ════════════════════════════════════════════════════════════════════════════
const ReportsPage = () => {
  const { user, organization } = useAuth();
  const [loading,           setLoading]           = useState(true);
  const [error,             setError]             = useState(null);
  const [reportType,        setReportType]        = useState('financial');
  const [financialData,     setFinancialData]     = useState(null);
  const [budgetPerformance, setBudgetPerformance] = useState(null);
  const [expenseTrends,     setExpenseTrends]     = useState(null);
  const [departmentData,    setDepartmentData]    = useState(null);
  const [exporting,         setExporting]         = useState(false);
  const [exportSuccess,     setExportSuccess]     = useState(false);

  // Filters
  const [fiscalYear,   setFiscalYear]   = useState('');
  const [months,       setMonths]       = useState('6');
  const [showFilters,  setShowFilters]  = useState(false);

  useEffect(() => { fetchReports(); }, [reportType, fiscalYear, months]); // eslint-disable-line

  const fetchReports = async () => {
    setLoading(true);
    setError(null);
    try {
      const params = {};
      if (fiscalYear) params.fiscalYear = fiscalYear;

      if (reportType === 'financial') {
        const res = await reportsAPI.getFinancial(params);
        if (res.data.success) setFinancialData(res.data.data);
        else setError(res.data.message || 'Failed to load financial report');
      } else if (reportType === 'budget') {
        const res = await reportsAPI.getBudgetPerformance(params);
        if (res.data.success) setBudgetPerformance(res.data.data);
        else setError(res.data.message || 'Failed to load budget performance');
      } else if (reportType === 'trends') {
        const res = await reportsAPI.getExpenseTrends({ ...params, months });
        if (res.data.success) setExpenseTrends(res.data.data);
        else setError(res.data.message || 'Failed to load expense trends');
      } else if (reportType === 'department') {
        const res = await reportsAPI.getDepartmentWise(params);
        if (res.data.success) setDepartmentData(res.data.data);
        else setError(res.data.message || 'Failed to load department report');
      }
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to load report. Make sure the backend is running.');
    } finally {
      setLoading(false);
    }
  };

  // ── PDF Export ─────────────────────────────────────────────────────────
  const handleExportPDF = async () => {
    const currentData = getCurrentData();
    if (!currentData) return;

    setExporting(true);
    try {
      await loadPDFLibs();

      const { jsPDF } = window.jspdf;
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      // jspdf-autotable attaches itself to jsPDF prototype automatically

      buildPDF(doc, reportType, currentData, user, organization);

      const titles = {
        financial : 'Financial_Report',
        budget    : 'Budget_Performance',
        trends    : 'Expense_Trends',
        department: 'Department_Report',
      };
      const ts = new Date().toISOString().split('T')[0];
      doc.save(`BudMap_${titles[reportType]}_${ts}.pdf`);

      setExportSuccess(true);
      setTimeout(() => setExportSuccess(false), 3000);
    } catch (err) {
      console.error('PDF export failed:', err);
      alert('PDF export failed. Please make sure jspdf and jspdf-autotable are installed:\nnpm install jspdf jspdf-autotable');
    } finally {
      setExporting(false);
    }
  };

  const getCurrentData = () => {
    if (reportType === 'financial')  return financialData;
    if (reportType === 'budget')     return budgetPerformance;
    if (reportType === 'trends')     return expenseTrends;
    if (reportType === 'department') return departmentData;
    return null;
  };

  const tabs = [
    { key: 'financial',  label: 'Financial',          Icon: FileBarChart },
    { key: 'budget',     label: 'Budget Performance', Icon: PieChart     },
    { key: 'trends',     label: 'Expense Trends',     Icon: TrendingUp   },
    { key: 'department', label: 'Department-wise',    Icon: FileBarChart },
  ];

  if (loading) return <div className="loader"><div className="loader-spinner"></div></div>;

  return (
    <div className="page-container">

      {/* ── Header ───────────────────────────────────────────────────────── */}
      <div className="page-header">
        <div className="page-header-content">
          <h2>Reports &amp; Analytics</h2>
          <p>Comprehensive financial insights for your organisation</p>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button
            className="btn btn-secondary"
            onClick={() => setShowFilters(f => !f)}
          >
            <Filter size={15} /> Filters
          </button>
          <button
            className="btn btn-primary"
            onClick={handleExportPDF}
            disabled={exporting || !getCurrentData()}
            title={!getCurrentData() ? 'Load a report first' : 'Download PDF'}
          >
            {exporting
              ? <RefreshCw size={16} style={{ animation: 'spin 1s linear infinite' }} />
              : <Download size={16} />}
            {exporting ? 'Generating…' : exportSuccess ? '✓ Downloaded!' : 'Export PDF'}
          </button>
        </div>
      </div>

      {/* ── Filter bar ───────────────────────────────────────────────────── */}
      {showFilters && (
        <div className="filters-bar">
          <div className="input-group" style={{ margin: 0 }}>
            <label className="input-label">Fiscal Year</label>
            <select className="filter-select" value={fiscalYear} onChange={e => setFiscalYear(e.target.value)}>
              <option value="">All Years</option>
              <option value="2022-23">2022-23</option>
              <option value="2023-24">2023-24</option>
              <option value="2024-25">2024-25</option>
              <option value="2025-26">2025-26</option>
            </select>
          </div>
          {reportType === 'trends' && (
            <div className="input-group" style={{ margin: 0 }}>
              <label className="input-label">Period</label>
              <select className="filter-select" value={months} onChange={e => setMonths(e.target.value)}>
                <option value="3">Last 3 months</option>
                <option value="6">Last 6 months</option>
                <option value="12">Last 12 months</option>
              </select>
            </div>
          )}
          <button className="btn btn-primary" onClick={fetchReports} style={{ alignSelf: 'flex-end' }}>
            <RefreshCw size={14} /> Apply
          </button>
        </div>
      )}

      {/* ── Tabs ─────────────────────────────────────────────────────────── */}
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
        {tabs.map(({ key, label, Icon }) => (
          <button
            key={key}
            className={`tab-btn ${reportType === key ? 'active' : ''}`}
            onClick={() => setReportType(key)}
          >
            <Icon size={15} />
            {label}
          </button>
        ))}
      </div>

      {/* ── Error ────────────────────────────────────────────────────────── */}
      {error && (
        <div style={{ display:'flex', alignItems:'center', gap:10, padding:'14px 18px', background:'#fef2f2', border:'1px solid #fecaca', borderRadius:10, color:'#dc2626', fontSize:13 }}>
          <AlertCircle size={16} style={{ flexShrink:0 }} />
          <span>{error}</span>
          <button onClick={fetchReports} style={{ marginLeft:'auto', background:'none', border:'none', color:'#dc2626', cursor:'pointer', fontWeight:600, fontSize:12 }}>
            Retry
          </button>
        </div>
      )}

      {/* ── Empty state ──────────────────────────────────────────────────── */}
      {!error && !loading && !getCurrentData() && (
        <div className="empty-state">
          <FileBarChart size={48} className="empty-state-icon" />
          <h3 className="empty-state-title">No report data available</h3>
          <p className="empty-state-text">No transactions or budgets recorded yet for this organisation.</p>
          <button className="btn btn-primary" style={{ marginTop:16 }} onClick={fetchReports}>
            <RefreshCw size={14} /> Refresh
          </button>
        </div>
      )}

      {/* ══════════════════════════════════════════════════════════════════
           FINANCIAL REPORT
      ══════════════════════════════════════════════════════════════════ */}
      {reportType === 'financial' && financialData && (
        <div className="report-content">
          <div className="report-summary">
            {[
              { label:'Total Income',   val: fmtNPR(financialData.summary.totalIncome),   cls:'green', Icon: TrendingUp   },
              { label:'Total Expense',  val: fmtNPR(financialData.summary.totalExpense),  cls:'red',   Icon: TrendingDown },
              { label:'Net Amount',     val: fmtNPR(financialData.summary.netAmount),     cls:'blue',  Icon: FileBarChart },
              { label:'Transactions',   val: financialData.summary.transactionCount || 0, cls:'green', Icon: Calendar     },
            ].map(({ label, val, cls, Icon }) => (
              <div key={label} className={`summary-card ${cls}`}>
                <Icon size={22} />
                <div><span className="summary-label">{label}</span><span className="summary-value">{val}</span></div>
              </div>
            ))}
          </div>

          {financialData.monthlyTrend?.length > 0 ? (
            <div className="charts-grid">
              <div className="chart-card">
                <h3>Monthly Income vs Expense</h3>
                <ResponsiveContainer width="100%" height={280}>
                  <BarChart data={financialData.monthlyTrend}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                    <XAxis dataKey="month" stroke="#94a3b8" fontSize={11} />
                    <YAxis stroke="#94a3b8" fontSize={11} />
                    <Tooltip contentStyle={TOOLTIP_STYLE} formatter={v => fmtNPR(v)} />
                    <Legend />
                    <Bar dataKey="income"  fill="#16a34a" name="Income"  radius={[4,4,0,0]} />
                    <Bar dataKey="expense" fill="#dc2626" name="Expense" radius={[4,4,0,0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
              {financialData.categoryBreakdown?.filter(c => c.type === 'expense').length > 0 && (
                <div className="chart-card">
                  <h3>Spending by Category</h3>
                  <ResponsiveContainer width="100%" height={280}>
                    <RechartsPie>
                      <Pie
                        data={financialData.categoryBreakdown.filter(c => c.type === 'expense').slice(0,6)}
                        cx="50%" cy="50%" innerRadius={55} outerRadius={95}
                        dataKey="amount" nameKey="name"
                        label={({ name, percent }) => `${name} ${(percent*100).toFixed(0)}%`}
                        labelLine={false}
                      >
                        {financialData.categoryBreakdown.slice(0,6).map((_, i) => (
                          <Cell key={i} fill={COLORS[i % COLORS.length]} />
                        ))}
                      </Pie>
                      <Tooltip contentStyle={TOOLTIP_STYLE} formatter={v => fmtNPR(v)} />
                    </RechartsPie>
                  </ResponsiveContainer>
                </div>
              )}
            </div>
          ) : (
            <div className="card" style={{ textAlign:'center', padding:'32px', color:'var(--gray-400)', fontSize:13 }}>
              No monthly data yet — add transactions to see charts.
            </div>
          )}

          {financialData.categoryBreakdown?.length > 0 && (
            <div className="card">
              <div className="card-header"><h3 className="card-title">Category Breakdown</h3></div>
              <div className="table-container">
                <table>
                  <thead><tr><th>Category</th><th>Type</th><th>Amount</th><th>Transactions</th></tr></thead>
                  <tbody>
                    {financialData.categoryBreakdown.map((c, i) => (
                      <tr key={i}>
                        <td style={{ fontWeight:600 }}>{c.name}</td>
                        <td><span className={`type-badge ${c.type}`}>{c.type}</span></td>
                        <td className={c.type === 'income' ? 'text-success' : 'text-error'}>{fmtNPR(c.amount)}</td>
                        <td>{c.count}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ══════════════════════════════════════════════════════════════════
           BUDGET PERFORMANCE
      ══════════════════════════════════════════════════════════════════ */}
      {reportType === 'budget' && budgetPerformance && (
        <div className="report-content">
          <div className="report-summary">
            {[
              { label:'Total Budgets',    val: budgetPerformance.summary.totalBudgets,                              cls:'blue',   Icon: FileBarChart },
              { label:'Total Budgeted',   val: fmtNPR(budgetPerformance.summary.totalBudgeted),                    cls:'green',  Icon: TrendingUp   },
              { label:'Total Spent',      val: fmtNPR(budgetPerformance.summary.totalSpent),                       cls:'red',    Icon: TrendingDown },
              { label:'Avg Utilization',  val: `${budgetPerformance.summary.averageUtilization}%`,                 cls:'yellow', Icon: PieChart     },
            ].map(({ label, val, cls, Icon }) => (
              <div key={label} className={`summary-card ${cls}`}>
                <Icon size={22} />
                <div><span className="summary-label">{label}</span><span className="summary-value">{val}</span></div>
              </div>
            ))}
          </div>

          {budgetPerformance.budgets?.length > 0 ? (
            <div className="card">
              <div className="card-header"><h3 className="card-title">Budget Details</h3></div>
              <div className="table-container">
                <table>
                  <thead>
                    <tr><th>Budget</th><th>Department</th><th>Total</th><th>Spent</th><th>Remaining</th><th>Utilization</th><th>Status</th></tr>
                  </thead>
                  <tbody>
                    {budgetPerformance.budgets.map((b, i) => (
                      <tr key={b.id || i}>
                        <td style={{ fontWeight:600 }}>{b.name}</td>
                        <td>{b.department}</td>
                        <td>{fmtNPR(b.totalAmount)}</td>
                        <td>{fmtNPR(b.spentAmount)}</td>
                        <td>{fmtNPR(b.remainingAmount)}</td>
                        <td>
                          <div className="utilization-cell">
                            <div className="mini-progress">
                              <div className={`mini-progress-fill ${b.utilizationRate > 90 ? 'danger' : b.utilizationRate > 70 ? 'warning' : ''}`}
                                style={{ width:`${Math.min(b.utilizationRate,100)}%` }} />
                            </div>
                            <span style={{ fontSize:12, fontWeight:600 }}>{b.utilizationRate}%</span>
                          </div>
                        </td>
                        <td>
                          <span className={`badge ${b.status === 'healthy' ? 'badge-success' : b.status === 'warning' ? 'badge-warning' : 'badge-error'}`}>
                            {b.status}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          ) : (
            <div className="card" style={{ textAlign:'center', padding:'32px', color:'var(--gray-400)', fontSize:13 }}>
              No budget data available yet.
            </div>
          )}
        </div>
      )}

      {/* ══════════════════════════════════════════════════════════════════
           EXPENSE TRENDS
      ══════════════════════════════════════════════════════════════════ */}
      {reportType === 'trends' && expenseTrends && (
        <div className="report-content">
          <div className="report-summary">
            {[
              { label:'Total Expense', val: fmtNPR(expenseTrends.summary.totalExpense),      cls:'red',    Icon: TrendingDown },
              { label:'Avg Monthly',   val: fmtNPR(expenseTrends.summary.avgMonthlyExpense), cls:'blue',   Icon: Calendar     },
              { label:'Total Income',  val: fmtNPR(expenseTrends.summary.totalIncome),       cls:'green',  Icon: TrendingUp   },
              { label:'Trend',         val: expenseTrends.trend,                             cls:'purple', Icon: TrendingUp   },
            ].map(({ label, val, cls, Icon }) => (
              <div key={label} className={`summary-card ${cls}`}>
                <Icon size={22} />
                <div>
                  <span className="summary-label">{label}</span>
                  <span className="summary-value" style={{ textTransform:'capitalize' }}>{val}</span>
                </div>
              </div>
            ))}
          </div>

          {expenseTrends.monthlyData?.length > 0 ? (
            <div className="chart-card">
              <h3>Income vs Expense — Last {expenseTrends.period?.months || 6} Months</h3>
              <ResponsiveContainer width="100%" height={320}>
                <AreaChart data={expenseTrends.monthlyData}>
                  <defs>
                    <linearGradient id="colorExp" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%"  stopColor="#dc2626" stopOpacity={0.2} />
                      <stop offset="95%" stopColor="#dc2626" stopOpacity={0}   />
                    </linearGradient>
                    <linearGradient id="colorInc" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%"  stopColor="#16a34a" stopOpacity={0.2} />
                      <stop offset="95%" stopColor="#16a34a" stopOpacity={0}   />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="month" stroke="#94a3b8" fontSize={11} />
                  <YAxis stroke="#94a3b8" fontSize={11} />
                  <Tooltip contentStyle={TOOLTIP_STYLE} formatter={v => fmtNPR(v)} />
                  <Legend />
                  <Area type="monotone" dataKey="income"  stroke="#16a34a" fill="url(#colorInc)" name="Income"  />
                  <Area type="monotone" dataKey="expense" stroke="#dc2626" fill="url(#colorExp)" name="Expense" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          ) : (
            <div className="card" style={{ textAlign:'center', padding:'32px', color:'var(--gray-400)', fontSize:13 }}>
              No trend data for this period.
            </div>
          )}

          {expenseTrends.topCategories?.length > 0 && (
            <div className="card">
              <div className="card-header"><h3 className="card-title">Top Expense Categories</h3></div>
              <div className="top-categories">
                {expenseTrends.topCategories.map((c, i) => (
                  <div key={i} className="category-item">
                    <div className="category-info">
                      <span className="category-rank">{i + 1}</span>
                      <span className="category-name">{c.name}</span>
                    </div>
                    <div className="category-stats">
                      <span className="category-amount">{fmtNPR(c.amount)}</span>
                      <span className="category-count">{c.count} transactions</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* ══════════════════════════════════════════════════════════════════
           DEPARTMENT-WISE
      ══════════════════════════════════════════════════════════════════ */}
      {reportType === 'department' && departmentData && (
        <div className="report-content">
          <div className="report-summary">
            {[
              { label:'Departments',     val: departmentData.summary.totalDepartments,       cls:'blue',  Icon: FileBarChart },
              { label:'Total Budgeted',  val: fmtNPR(departmentData.summary.totalBudgeted),  cls:'green', Icon: TrendingUp   },
              { label:'Total Spent',     val: fmtNPR(departmentData.summary.totalSpent),     cls:'red',   Icon: TrendingDown },
              { label:'Transactions',    val: departmentData.summary.totalTransactions,      cls:'yellow',Icon: Calendar     },
            ].map(({ label, val, cls, Icon }) => (
              <div key={label} className={`summary-card ${cls}`}>
                <Icon size={22} />
                <div><span className="summary-label">{label}</span><span className="summary-value">{val}</span></div>
              </div>
            ))}
          </div>

          {departmentData.departments?.length > 0 ? (
            <>
              {/* Bar chart */}
              <div className="chart-card">
                <h3>Budget vs Spent by Department</h3>
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={departmentData.departments}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                    <XAxis dataKey="name" stroke="#94a3b8" fontSize={11} />
                    <YAxis stroke="#94a3b8" fontSize={11} />
                    <Tooltip contentStyle={TOOLTIP_STYLE} formatter={v => fmtNPR(v)} />
                    <Legend />
                    <Bar dataKey="totalBudgeted" fill="#16a34a" name="Budgeted" radius={[4,4,0,0]} />
                    <Bar dataKey="totalSpent"    fill="#dc2626" name="Spent"    radius={[4,4,0,0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>

              {/* Table */}
              <div className="card">
                <div className="card-header"><h3 className="card-title">Department Details</h3></div>
                <div className="table-container">
                  <table>
                    <thead>
                      <tr><th>Department</th><th>Head</th><th>Budgeted</th><th>Spent</th><th>Remaining</th><th>Utilization</th><th>Transactions</th></tr>
                    </thead>
                    <tbody>
                      {departmentData.departments.map((d, i) => (
                        <tr key={d.id || i}>
                          <td style={{ fontWeight:600 }}>{d.name}</td>
                          <td>{d.head}</td>
                          <td>{fmtNPR(d.totalBudgeted)}</td>
                          <td>{fmtNPR(d.totalSpent)}</td>
                          <td>{fmtNPR(d.remainingBudget)}</td>
                          <td>
                            <div className="utilization-cell">
                              <div className="mini-progress">
                                <div className={`mini-progress-fill ${d.utilizationRate > 90 ? 'danger' : d.utilizationRate > 70 ? 'warning' : ''}`}
                                  style={{ width:`${Math.min(d.utilizationRate,100)}%` }} />
                              </div>
                              <span style={{ fontSize:12, fontWeight:600 }}>{d.utilizationRate}%</span>
                            </div>
                          </td>
                          <td>{d.transactionCount}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </>
          ) : (
            <div className="card" style={{ textAlign:'center', padding:'32px', color:'var(--gray-400)', fontSize:13 }}>
              No department data available yet.
            </div>
          )}
        </div>
      )}

    </div>
  );
};

export default ReportsPage;
